version: '3'

services:
  document-converter:
    build: .
    container_name: document-converter
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - UPLOAD_DIR=/app/data/uploads
      - OUTPUT_DIR=/app/data/output
      - LIBREOFFICE_HOST=localhost
      - LIBREOFFICE_PORT=2002
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
